auc_homepage:
    path:     /
    defaults: { _controller: AUCBundle:Noticia:list }

auc_futbol_convencional:
    path:     /futbol_convencional
    defaults: { _controller: AUCBundle:Equipo:all }

auc_futbol_silla:
    path:     /futbol_silla_ruedas
    defaults: { _controller: AUCBundle:Default:futbolsilla }

auc_extra:
    path:     /actividades
    defaults: { _controller: AUCBundle:Default:extra }

auc_equipo:
    path:     /futbol/equipo/{id_equipo}
    defaults: { _controller: AUCBundle:Equipo:plantilla, id_equipo:1 }

auc_noticia:
    path:     /noticia/{id}
    defaults: { _controller: AUCBundle:Noticia:noticia}

auc_bienvenido:
    path:     /bienvenido
    defaults: { _controller: AUCBundle:Default:bienvenido }

auc_register_admin:
    path:     admin/register
    defaults: { _controller: AUCBundle:Admin:register }

auc_login_admin:
    path:     /admin
    defaults: { _controller: AUCBundle:Admin:login }

auc_logout_admin:
    path:     /admin/logout

auc_contacto:
    path:     /contacto
    defaults: { _controller: AUCBundle:Mail:contact }

auc_quienes:
    path:     /nosotros
    defaults: { _controller: AUCBundle:Default:nosotros }

auc_adaptado:
    path:     /futbol_adaptado
    defaults: { _controller: AUCBundle:Default:adaptado }

auc_exito:
    path:     /exito
    defaults: { _controller: AUCBundle:Default:exito }
